### ISSUE TITLE
可以遍历结构类型吗

### ISSUE THREAD

**Issue by liwei1024** [wqking/metapp#2]
可以遍历结构类型吗

**Comment by wqking** [comment]
Yes, struct is same as class. You can check [the tutorial](https://github.com/wqking/metapp/blob/master/doc/tutorial/tutorial_metaclass.md), [document](https://github.com/wqking/metapp/blob/master/doc/interfaces/metaclass.md)

**Comment by liwei1024** [comment]
可以不用定义什么直接遍历结构字段类型吗 我想弄一个二进制序列化工具 在找一个可以遍历任意结构字段的库

**Comment by wqking** [comment]
No, it can't, you have to register the meta information.
